---
title: "Graphs"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    source_code: embed
    runtime: shiny
    theme: cosmo
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(shiny)
library(readxl)
```

```{r}
final = read_excel("./data/median-earnings-2016-final.xlsx", sheet =1, range = "A5:Q563") %>% 
  janitor::clean_names() %>%
  select(-starts_with("moe")) 

final_num = final %>% 
  select(-ends_with("med")) %>%
  pivot_longer(cols = starts_with("est"), names_to = "gender", values_to = "number", values_drop_na = FALSE) %>% 
  filter(occupational_category %in% c("Management, Business, Science, and Arts Occupations", "Service Occupations", "Sales and Office Occupations", "Natural Resources, Construction, and Maintenance Occupations", "Production, Transportation, and Material Moving Occupations")) %>% 
  filter(gender %in% c("est_men_num", "est_women_num")) %>% 
  mutate(gender = recode(gender, "est_men_num" = "Men", "est_women_num" = "Women"))


final_med = final %>% 
  select(-ends_with("num")) %>%
  mutate_at(vars(starts_with("est")), as.numeric) %>% 
  pivot_longer(cols = starts_with("est"), names_to = "gender", values_to = "number", values_drop_na = FALSE) %>% 
  filter(occupational_category %in% c("Management, Business, Science, and Arts Occupations", "Service Occupations", "Sales and Office Occupations", "Natural Resources, Construction, and Maintenance Occupations", "Production, Transportation, and Material Moving Occupations")) %>% 
  filter(gender %in% c("est_men_med", "est_women_med")) %>% 
  mutate(gender = recode(gender, "est_men_med" = "Men", "est_women_med" = "Women"))


```

Column {data-width=200}
--------------------------------------------------------------------------------------
```{r}

salary = final_num %>% pull(gender) %>% unique()
checkboxGroupInput("gender_choice", label = h5("Select Count"), choices = salary, selected = salary)

#salary = final_num %>% pull(occupational_category) %>% unique()
#checkboxGroupInput("gender_choice", label = h5("Select Category"), choices = salary, selected = salary)

median = final_med %>% pull(gender) %>% unique()
checkboxGroupInput("gender_median", label = h5("Select Median"), choices = median, selected = median)

#salary = final_med %>% pull(occupational_category) %>% unique()
#checkboxGroupInput("gender_median", label = h5("Select Categroy"), choices = salary, selected = salary)
```

Column 
---------------------------------------------------------------------------

### Male and Female Employees in each Industry

```{r}
renderPlotly({
  final_num %>% 
  filter(gender == input$gender_choice) %>% 
  ggplot(aes(x = occupational_category, y = number, fill = gender)) +
  geom_bar(stat = "identity", position = "dodge") +
  scale_y_continuous(breaks = seq(2000000, 100000000, 3000000)) +
  scale_fill_grey() +
  theme(axis.text.x = element_text(size=10), legend.position = "none") +
  scale_x_discrete(labels = c("Management", "Natural", "Production", " Sales", "Service"))
})
```


### Median Income of Males vs Females in each Industry

```{r}
renderPlotly({
  final_med %>% 
  filter(gender == input$gender_median) %>% 
  ggplot(aes(x = occupational_category, y = number, fill = gender)) +
  geom_bar(stat = "identity", position = "dodge") +
  scale_y_continuous(breaks = seq(20000, 80000, 10000)) +
  scale_fill_grey() +
  theme(axis.text.x = element_text(size=10)) +
  scale_x_discrete(labels = c("Management", "Natural", "Production", " Sales", "Service")) 
})

```

